config:
    send_anonymous_usage_stats: False
    use_colors: True

deployment:
  target: postgres
  outputs:
    postgres:
      type: postgres
      host: "{{ env_var('DBT_HOST') }}"
      user: "{{ env_var('DBT_USER') }}"
      pass: "{{ env_var('DBT_PASSWORD') }}"
      port: "{{ env_var('DBT_PORT') }}"
      dbname: "{{ env_var('DBT_DATABASE') }}"
      schema: "Postgres"
      threads: 5