version: 2

sources:
  - name: salesforce
    tables:
      - name: account
      - name: act_on_instance_c
      - name: act_on_instance_user_c
      - name: campaign_influence
      - name: campaign_member
      - name: campaign
      - name: contact_history
      - name: contact
      - name: contract
      - name: fivetran_formula
      - name: lead_history
      - name: lead
      - name: opportunity
      - name: opportunity_field_history
      - name: opportunity_line_item
      - name: opportunity_contact_role
      - name: profile
      - name: product_2
      - name: sbqq_quote_line_c
      - name: task
      - name: user
  - name: data_studio_s3
    tables:
      - name: data_studio_emails
      - name: data_studio_forms
      - name: data_studio_landingpages
      - name: data_studio_media
      - name: data_studio_webinars
      - name: data_studio_webpages
  - name: common
    tables:
      - name: kpi_targets
      - name: kpi_targets_2022
      - name: gauge_placeholder
      - name: date_base
      - name: demand_gen_cost_fy23
      - name: placeholder
      - name: fy23_custom_touch_points
      - name: fy23_sdr_sqo_targets
      - name: fy23_webinars
      - name: fy23_webpages
      - name: campaign_type_date_base
  - name: outreach_sf
    tables:
      - name: account
      - name: email_address
      - name: mailing
      - name: opportunity
      - name: prospect
      - name: prospect_email
      - name: prospect_tag
      - name: sequence
      - name: sequence_state
      - name: sequence_tag
      - name: task
      - name: users
  - name: Facts
    tables:
      - name: attribution_9883